export const rehabProgressCopy = {
  uk: {
    title: "Прогрес пацієнта",
    eyebrow: "SPRINT AI · Поздовжній аналіз руху",
    subtitle:
      "Порівнюйте сумісні реабілітаційні сесії та обговорюйте зміну ROM, симетрії й виконання цілі.",
    patient: "Пацієнт",
    language: "Мова",
    prototype: "Дослідницький прототип",
    localData: "Локальні дані",
    newAnalysis: "Новий аналіз",
    sessions: "сесії",
    latest: "Остання",
    baseline: "Базова сесія",
    current: "Поточна сесія",
    leftRom: "ROM ліворуч",
    rightRom: "ROM праворуч",
    symmetry: "Симетрія",
    completion: "Досягнення цілі",
    repetitions: "Повтори",
    change: "Зміна між першою та останньою сумісною сесією",
    trendTitle: "Динаміка вимірювань",
    trendSubtitle: "ROM у градусах та симетрія у відсотках",
    observationTitle: "Професійне спостереження",
    timelineTitle: "Хронологія сесій",
    timelineSubtitle: "Реальні збережені результати вибраного протоколу",
    frames: "валідних кадрів",
    video: "відео",
    noVideo: "без відео",
    oneSessionTitle: "Зафіксовано базову сесію",
    oneSessionBody:
      "Потрібна ще одна сумісна сесія, щоб описати зміну в часі.",
    emptyTitle: "Ще немає збережених реабілітаційних сесій",
    emptyBody:
      "Проведіть аналіз наживо або завантажте відео та збережіть результат в історію.",
    loadError: "Не вдалося завантажити прогрес",
    loadErrorBody:
      "Перевірте локальний backend і повторіть запит. Дані не змінено.",
    retry: "Спробувати ще раз",
    loading: "Завантаження збережених вимірювань…",
    limitation:
      "Ці значення підтримують професійне обговорення руху. Вони не встановлюють діагноз, не доводять ефект лікування і мають інтерпретуватися разом із клінічним контекстом.",
  },
  en: {
    title: "Patient progress",
    eyebrow: "SPRINT AI · Longitudinal movement analysis",
    subtitle:
      "Compare compatible rehabilitation sessions and discuss change in ROM, symmetry, and target completion.",
    patient: "Patient",
    language: "Language",
    prototype: "Research prototype",
    localData: "Local data",
    newAnalysis: "New analysis",
    sessions: "sessions",
    latest: "Latest",
    baseline: "Baseline session",
    current: "Current session",
    leftRom: "Left ROM",
    rightRom: "Right ROM",
    symmetry: "Symmetry",
    completion: "Target completion",
    repetitions: "Repetitions",
    change: "Change between the first and latest compatible sessions",
    trendTitle: "Measurement trend",
    trendSubtitle: "ROM in degrees and symmetry in percent",
    observationTitle: "Professional observation",
    timelineTitle: "Session timeline",
    timelineSubtitle: "Real persisted results for the selected protocol",
    frames: "valid frames",
    video: "video",
    noVideo: "no video",
    oneSessionTitle: "Baseline session recorded",
    oneSessionBody:
      "One more compatible session is required to describe change over time.",
    emptyTitle: "No saved rehabilitation sessions yet",
    emptyBody:
      "Run a live analysis or upload a video, then save the result to history.",
    loadError: "Could not load progress",
    loadErrorBody:
      "Check the local backend and retry. No stored data was changed.",
    retry: "Try again",
    loading: "Loading persisted measurements…",
    limitation:
      "These values support professional movement discussion. They do not diagnose, prove treatment effect, or replace interpretation alongside the clinical context.",
  },
} as const;
